version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./content:/usr/share/nginx/html
    ports:
      - "3005:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
