#!/usr/bin/env bash
#
# Download original video content from YouTube using yt-dlp
#
# Usage: ./utils/download.sh
#
# Copyright (c) 2024 AVEQ GmbH.
# License: MIT

set -e

cd "$(dirname "$0")/.."

CONTENT_ORIGINAL_DIR=content_original

# Video URLs and their expected filenames (as generated by yt-dlp default naming)
declare -A videos=(
  ["https://youtu.be/aqz-KE-bpKQ"]="Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film [aqz-KE-bpKQ]"
  ["https://youtu.be/UXqq0ZvbOnk"]="CHARGE - Blender Open Movie [UXqq0ZvbOnk]"
  ["https://youtu.be/u9lj-c29dxI"]="WING IT! - Blender Open Movie [u9lj-c29dxI]"
  ["https://youtu.be/R6MlUcmOul8"]="Tears of Steel - Blender VFX Open Movie [R6MlUcmOul8]"
)

# Check if yt-dlp is installed
if ! command -v yt-dlp &>/dev/null; then
  echo "Error: yt-dlp is not installed."
  echo "Install it from: https://github.com/yt-dlp/yt-dlp"
  exit 1
fi

mkdir -p "$CONTENT_ORIGINAL_DIR"
cd "$CONTENT_ORIGINAL_DIR"

downloaded=0
skipped=0

for url in "${!videos[@]}"; do
  base_name="${videos[$url]}"

  # Check if complete file already exists (final merged formats only, not partial .fXXX. files)
  if ls "${base_name}".{webm,mkv,mp4} 1>/dev/null 2>&1; then
    echo "Skipping: ${base_name} (already exists)"
    skipped=$((skipped + 1))
  else
    # Remove any partial downloads before retrying
    rm -f "${base_name}".f*.* "${base_name}".part 2>/dev/null || true
    echo "Downloading: ${base_name}"
    yt-dlp "$url"
    downloaded=$((downloaded + 1))
  fi
done

echo
echo "Done. Downloaded: $downloaded, Skipped: $skipped"
